# Generated by Django 4.2.3 on 2023-07-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientDashboard', '0002_clientusers_groups_clientusers_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientusers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
