# Generated by Django 4.2.3 on 2023-07-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientDashboard', '0003_alter_clientusers_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientusers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
