# Generated by Django 4.2.3 on 2023-07-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientDashboard', '0004_alter_clientusers_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientusers',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
