# Generated by Django 4.2.3 on 2023-07-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientDashboard', '0005_clientusers_is_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientusers',
            name='access_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clientusers',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
