# Generated by Django 4.0.2 on 2023-07-09 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClientDashboard', '0008_blacklistedtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistedToken',
        ),
    ]
