# Generated by Django 4.0.2 on 2023-07-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientDashboard', '0009_delete_blacklistedtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientusers',
            name='username',
        ),
        migrations.AddField(
            model_name='clientusers',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientusers',
            name='user_type',
            field=models.CharField(choices=[('homeowner', 'Homeowner'), ('contractor', 'Contractor')], default='homeowner', max_length=20),
        ),
    ]
