# Generated by Django 4.0.2 on 2023-07-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientDashboard', '0010_remove_clientusers_username_clientusers_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientusers',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
