# Generated by Django 4.0.2 on 2023-07-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClientDashboard', '0011_clientusers_token_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientusers',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='clientusers',
            name='is_logged_in',
        ),
        migrations.RemoveField(
            model_name='clientusers',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='clientusers',
            name='token_expires_at',
        ),
    ]
