# Generated by Django 4.0.2 on 2023-07-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientDashboard', '0012_remove_clientusers_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientusers',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
