# Generated by Django 4.0.2 on 2023-07-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientDashboard', '0013_clientusers_is_logged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientusers',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
