# Generated by Django 4.0.2 on 2023-07-16 12:11

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ClientDashboard', '0015_userdesignform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdesignform',
            name='request_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('solar_preliminary_design', 'Solar Preliminary Design'), ('solar_permit_plan', 'Solar Permit Plan'), ('engineering_stamp', 'Engineering Stamp'), ('interconnection_and_permitting_service', 'Interconnection and Permitting Service')], max_length=50, null=True),
        ),
    ]
