# Generated by Django 4.0.2 on 2023-07-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientDashboard', '0017_userdesignform_more_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientusers',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
