# Generated by Django 4.0.2 on 2023-07-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClientDashboard', '0018_alter_clientusers_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdesignform',
            name='job_address',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
